### ISSUE TITLE
Add exhaustive checks for errors in contracts

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#105]
Some contracts (like subkeys) have error conditions / cases that are not being triggered / checked in unit tests. Let's add those for completeness.

**Comment by ethanfrey** [comment]
This is too vague.
Can you please give some concrete examples so we can make PRs to fix them (can be new issues per contract, or adding a checklist to this issue). If they have been since fixed, let's close this.

**Comment by maurolacy** [comment]
This was useful as an initial task for @hashedone to get used to the framework.

I would say, let's close this, and in any case create specific issues to improve testing, and the test framework / techniques.

**Comment by maurolacy** [comment]
Closing as too vague / general.
