### ISSUE TITLE
Unify multisig structs Member and VoterResponse

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#151]
Currently we have not two but three similar structs in multisig code, `Voter`, `Member` and `VoterResponse`.

Unify them into a common struct (`Voter` sounds like a good name), even when it implies introducing an explicit dependency between fixed-multisig and flex-multisig.

**Comment by ethanfrey** [comment]
Do we still want to do this? Is it done?

**Comment by maurolacy** [comment]
This is trivial to do, but not yet done. I'll assign it to me and see that it's closed.

**Comment by maurolacy** [comment]
OK, what's happening with these structs is that one set is in the context of `cw3` (multisig) and the other is in the context of `cw4` (groups).

In particular:

- `cw3::VoterResponse` is identical to `cw4::MemberResponse`.
- `cw3.:VoterDetail` is identical to `cw4::Member`.

Now, given that `cw4` is a late / more recent spec, I don't think it makes sense to introduce a dependency between the older `cw3` spec and the newer `cw4` spec (That is, mapping the cw3 voters to cw4 members).

And, the other way around (mapping cw4 members to cw3 voters) doesn't make so much sense: A voter will in general be a member (of something), but a member wouldn't necessarily be a voter.

So, I think the sanest and simplest thing to do, is **closing this without any changes**.

**Comment by ethanfrey** [comment]
> So, I think the sanest and simplest thing to do, is closing this without any changes.

Sounds good. 
The most maintainable PR is the PR never write
