### ISSUE TITLE
Raw Query: make usage simpler and visible

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/cw-plus#325]
Raw Query is the most efficient form of making cross contract queries, altough among community I see a tendency of using smart query when raw query can be used. Providing raw query generation helpers along the code would make raw queries promoted and increase in usage.

**Comment by orkunkl** [comment]
Actually found out the queries are provided in the [helpers](http://github.com/CosmWasm/cosmwasm-plus/blob/c6f86638454b97a4974216be24afc6b6296bb65a/packages/cw20/src/helpers.rs#L55-L63). But it uses Smart Query where Raw Query would work.

**Comment by ethanfrey** [comment]
Would this be addressed by #376 and the corresponding helper for Map?

**Comment by orkunkl** [comment]
Yes, #376 serves the same purpose
