### ISSUE TITLE
Define generic multitest module

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cw-plus#387]
Related to #266

Something like `Bank = Module<BankMsg, BankQuery>`.

We can have a default NotImplemented implementation that we can use to handle all the other unsupported types of CosmosMsg, but include them in the switch. All have the same interface, which allows us to easy add support for other modules (Custom, Staking, IBC) without changing everything else.

Router should include multiple modules for these main types, but `::new()` will just set as `NotImplemented`.

**Comment by hashedone** [comment]
I was looking on this idea for half a day and I don't think it makes any sense. Those modules are not the same - Api is differing, as all modules should react on different enum variant.

Also most modules should probably contain no logic - just be mocked structures. I would just proceed with extracting better setup API (via #388), and then prepare transparent mockups of all needed subcomponents with `mockall`.
