### ISSUE TITLE
Accept &QuerierWrapper not &Querier in helpers

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cw-plus#390]
This has come up a few times and it seems to not be so usable currently. Most code has `Deps` or `DepsMut`, which contains `&QuerierWrapper`. However, the helpers [want a `Querier`](https://github.com/CosmWasm/cw-plus/blob/main/packages/cw721/src/helpers.rs#L52) only to later [cast it to a `QuerierWrapper`](https://github.com/CosmWasm/cw-plus/blob/main/packages/cw721/src/helpers.rs#L45).

That plus the generic `Q: Querier` condition makes it very hard to use. Let's make these easier to use. (All of them, not just the cw721 in the example)

**Comment by ivanfong01** [comment]
I dun think this is closed? As the commit was rejected. Cw20 helper iss still using &Querier

**Comment by ethanfrey** [comment]
Yes, this is still an error. What happened to the above patch?
Let's get this fixed finally

**Comment by uint** [comment]
Done in #839
