### ISSUE TITLE
Remove use of dyn in multitest Router

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cw-plus#404]
for Storage, Api, Querier, we should stick with dyn, as that is what we pass into Deps and we have no real need for more details. For the other, it can be useful to get the original types when setting up test code.

I am talking about:

```rust
pub struct Router<ExecC, QueryC> {
    pub(crate) wasm: Box<dyn Wasm<ExecC, QueryC>>,
    pub(crate) bank: Box<dyn Bank>,
    pub(crate) custom: Box<dyn CustomHandler<ExecC, QueryC>>,
}
```

https://github.com/CosmWasm/cw-plus/blob/mt-msg-handling/packages/multi-test/src/app.rs#L254-L258

I would propose something like the follow:

```rust
pub struct Router<ExecC, QueryC, W: Wasm<ExecC, QueryC>, B: Bank, C: CustomHandler<ExecC, QueryC>> {
    pub(crate) wasm: Box<W>,
    pub(crate) bank: Box<B>,
    pub(crate) custom: Box<C>,
}
```

It would require some changes to the builder pattern (but we have a similar setup in ContractWrapper where we change types during the builder.

**Comment by hashedone** [comment]
Basically I very much like this approach. Two things which I would already note:
* If you don't have `dyn Trait`s, you nevermore need boxing - just keep stuff by ownership. You need box to handle unsized types, but there is no need to accept unsized generics.
* I really don't like trait bounds in types. They doesn't give anything, but propagates quickly (if I use the type anywhere, I immediately have to add bounds - even if I don't need to use impl of it). Basically I find it way better to add bounds only to impl block (where you have to add it anyway). There is an argumentation that maybe at some point in future implied bounds would be there, but it doesn't look like it would happen anytime soon if ever.

**Comment by ethanfrey** [comment]
Does this also close https://github.com/CosmWasm/cw-plus/issues/362 in the refactor?
Or is that a separate issue still?
