### ISSUE TITLE
storage-plus: Improve in-code documentation of map primitives, in particular `MultiIndex`

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/cw-plus#407]
I found some storage-plus primitives not documented or poorly documented, and I think it should be improved. I know some of them are used around and those usages can be taken as an example (also including tests which are in pretty good shape there), but it takes way more time than reading doc comments (which IDEs are just bringing on hover), not mentioning generating doc with cargo.

Just as an example `MultiIndex::new` - there is no single word what is the second argument of the `idx_fn` (also no single word about first one, but it is kind of easier to deduce). Also there is really not good explanation how to use it, and why to include the second `idx_fn` argument as part of key.

**Comment by maurolacy** [comment]
There's an explanation that addresses some of those points in the docs:

https://docs.cosmwasm.com/tutorials/storage/indexes/

Feel free to suggest updates / clarifications,  and / or to extend on it.

**Comment by maurolacy** [comment]
Perhaps an issue must be opened in the [docs](https://github.com/CosmWasm/docs), so that those changes / suggestions can be easily tracked.
