### ISSUE TITLE
Contracts for Token Sale and Vesting period

### ISSUE THREAD

**Issue by logesh2496** [CosmWasm/cw-plus#444]
Request to add Token Sale contract and Vesting period contract as also mentioned in the issue: https://github.com/CosmWasm/cw-examples/issues/60

**Comment by ethanfrey** [comment]
This is a nice idea, but out of scope for Confio.
Please check out github.com/InterWasm/DAO which should be taking over such projects

Also see the introduction: https://medium.com/cosmwasm/future-of-cosmwasm-ecosystem-development-ba0fc477cbc4
