### ISSUE TITLE
Add url as input when mint cw1155

### ISSUE THREAD

**Issue by ALPAC-4** [CosmWasm/cw-plus#449]
There are no way to put `url` in cw1155 at the base code but the query that call url is exist.
```
Cw1155QueryMsg::TokenInfo { token_id } => {
    let url = TOKENS.load(deps.storage, &token_id)?;
    to_binary(&TokenInfoResponse { url })
}
```

So I think adding url as input at excute_mint function is reasonable.

**Comment by ethanfrey** [comment]
Is this for an NFT project?

Can you check out the brand new https://github.com/CosmWasm/cw-nfts repo?

We are trying to move all not related work there. If cw1155 work is primarily about NFTs, then maybe we can move that over as well.

**Comment by ALPAC-4** [comment]
I know some projects that using ERC1155 for NFT (like SAND). 
And currently I'm doing some research about NFT for some reasons. 
That's why I also look into CW1155. 

The purpose of the opening issue was just curious that why there is the queryMsg that call url, even there are no way to put in. 

And good to hear about the cw-nfts repo. It just a personal opinion but CW1155 can be in there too.

**Comment by ethanfrey** [comment]
@yihuang wrote cw1155 contract I believe. Maybe he can answer. And also discuss if he wishes to move it to cw-nfts

**Comment by yihuang** [comment]
Yeah, I guess either set URL when mint or a dedicated message to manage the metadata URL is fine, no strong opinions on that.

**Comment by ethanfrey** [comment]
@ALPAC-4 do you want to make a PR for this change? To add metadata url on mint?

We can discuss moving repos after the next release

**Comment by JakeHartnell** [comment]
> @yihuang wrote cw1155 contract I believe. Maybe he can answer. And also discuss if he wishes to move it to cw-nfts

Once we feel good about the base `cw721` contract, we're definitely going to be working on `cw1155`.

**Comment by ALPAC-4** [comment]
> > @yihuang wrote cw1155 contract I believe. Maybe he can answer. And also discuss if he wishes to move it to cw-nfts
> 
> Once we feel good about the base `cw721` contract, we're definitely going to be working on `cw1155`.

Thanks for all your effort. I'm not a RUST dev. (I can just read some code) So I'll waiting for you. Thanks a lot

**Comment by ethanfrey** [comment]
I'm closing this here.

@JakeHartnell is taking this over in cw-nfts repo (linked above)
