### ISSUE TITLE
Gas limits for queries

### ISSUE THREAD

**Issue by alwin-peng** [CosmWasm/cw-plus#458]
It would be nice to be able to set a gas limit for a contract query. This way, we can query arbitrary contracts from another contract and not really worry about out of gas issues or panics.

**Comment by ethanfrey** [comment]
There is no way to do that in cosmwasm 1.0. The best you can do is run a submessage with a gas limit, and in that submessage do the query. 

Panics in the called contract are returned as an error in the query (which can be handled). There is no protection against infinite gas usage.
