### ISSUE TITLE
Add non-owned `range_de`

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#463]
Use lifetimes / references to create a non-owned approach to key deserialization, if possible. Not sure if this is actually possible, as these keys come from storage, and are an ephemeral / referenced type (`&[u8]`) already.
 
`serde` has a `Deserialize` trait that works with references, as well as a `DeserializeOwned` one. Let's take a look at it to understand it better, and see if a similar approach can be applied here.

**Comment by ethanfrey** [comment]
Update here?

Is this possible or not? If possible, is there any idea how to proceed?

No need to start on it, but it would be great to document an approach that could work. Or close it as "won't fix" (I kind of feel the second one, as I am unsure this is possible)

**Comment by maurolacy** [comment]
Closing / archiving this, as we are not sure how to do it, or if it's possible at all.
