### ISSUE TITLE
Various `range_de` / `prefix_de` improvements

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#464]
A number of slight improvements to the current impl:

- [x] ~~Replace `KeyDeserializer::from_slice(&[u8])` with `KeyDeserializer::from_vec(Vec<u8>)`. When we call it, we can consume the Vec and save a clone. See [deserialize_kv](https://github.com/CosmWasm/cw-plus/pull/432/files#diff-b74fe4efaced9c75072d3e90271006a9952c20fb129a418deb54561d5b67ed96R22).~~ (done in #467)
- [x] ~~Make a `K::Owned: Deserializable` trait attribute. `String`, `Vec<u8>` would have `type Deserializable = Self`. `&str` would have `type Deserializable = String`, for example. The idea behind this is to try to avoid having to declare `K` as `Deserializable`, that is, moving / enforcing the `Deserializable` bound to `K::Output` instead.~~ (won't do)
- [x] ~~Add a `from_length_prefixed` helper, and use it / call it where needed~~. (not needed with key deserialization already working) 

#432 follow-up.

**Comment by ethanfrey** [comment]
> Replace KeyDeserializer::from_slice(&[u8]) with KeyDeserializer::from_vec(Vec<u8>). When we call it, we can consume the Vec and save a clone.

I would be happy to see this as a small PR first, and fit it in 0.10.0. The rest can follow later.

**Comment by maurolacy** [comment]
> > Replace KeyDeserializer::from_slice(&[u8]) with KeyDeserializer::from_vec(Vec). When we call it, we can consume the Vec and save a clone.
> 
> I would be happy to see this as a small PR first, and fit it in 0.10.0. The rest can follow later.

Working on this, but my take is that a method `from_vec(Vec<u8>)` is similar / equivalent to from_slice(&[u8])`, in terms of memory management / number of clones.

In the first case, we pass an owned value, that we can use / consume. But, this value is being copied as argument, when calling the function.
In the second case, we pass a reference, but then we need to clone it when we want to consume it / return it.

A third option would be to have a signature like `from_vec(&Vec<u8>)`; but this is similar to passing a reference to a slice. In fact, a slice reference is simpler, because `try_from` works on it directly, when needed.

I can publish the PR if you want, but my opinion is we leave this just as it is. In the case of a "raw" deserialization to `Vec<u8>` we will have a useless call to the function, but still, no extra copy will be done.

Perhaps adding `#inline` can be used, to avoid the extra call.

**Comment by ethanfrey** [comment]
> In the first case, we pass an owned value, that we can directly use / consume. But, this value is being copied as argument, when calling the function.

No, the one place this is called in non-test code, we have `(Vec<u8>, Vec<u8>)` as input.
We take the first Vec by reference here, where we often use it as is (no copy).
That Vec drops out of scope by the end of `deserialise_kv` closure, so it is no cost to move it, as we don't need to clone it and drop it otherwise.

**Comment by ethanfrey** [comment]
If you want to support both calls in the trait, with a default implementation that `from_vec` will simply call `from_slice`, then that is fine. And override it for the ones where we can reuse the Vec.

**Comment by maurolacy** [comment]
You say that that argument is not being copied? I guess we would need to inspect that with a debugger, to be sure.

**Comment by maurolacy** [comment]
> If you want to support both calls in the trait, with a default implementation that `from_vec` will simply call `from_slice`, then that is fine. And override it for the ones where we can reuse the Vec.

OK, I'll do that.

**Comment by maurolacy** [comment]
See #467.

**Comment by ethanfrey** [comment]
> You say that that argument is not being copied? I guess we would need to inspect that with a debugger, to be sure.

Huh? I am just saying that we don't need to add a clone to convert current usage of `from_slice` to `from_vec`.

Supporting both is more flexible if we do call it other places.

**Comment by maurolacy** [comment]
We now support both.

And, come to think of it, if the compiler is optimizing it will notice that the owned argument of `to_vec` is never used again, and that it can then be passed without copy. So, this version would be definitely better.
