### ISSUE TITLE
Deprecate `IntKey`

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#472]
We can implement `PrimaryKey` over integer types easily using macros.

Like in https://github.com/CosmWasm/cw-plus/blob/d536358fb9bc45a43a9e055ed05f59f0998ba03a/packages/storage-plus/src/de.rs#L99-L111

and then https://github.com/CosmWasm/cw-plus/blob/d536358fb9bc45a43a9e055ed05f59f0998ba03a/packages/storage-plus/src/de.rs#L113

That means, we can remove the need for `IntKey`, and use the integer values directly. So, better usability, clarity, and user experience in general.

**Comment by ethanfrey** [comment]
We cannot currently do this as PrimaryKey has `key(&self) -> Vec<&[u8]>` which is efficient for bytes and string, but cannot be implemented on `u32`.

Proposal by @hashedone to use some associated type on the trait, `type KeyType: AsRef<[u8]>`.

**Comment by ethanfrey** [comment]
If you do this in a backwards-compatible way that doesn't break the current usage of IntKey, then I would be happy to get this in 0.10.0. And we just deprecate the IntKey in 0.11.0 (rather than some warnings popping up in a patch release)

**Comment by ueco-jb** [comment]
Followed up in #549.
