### ISSUE TITLE
Incorrect I32Key Index Ordering

### ISSUE THREAD

**Issue by Ruborcalor** [CosmWasm/cw-plus#489]
When using an I32Key as the primary key for an index, the ordering is done incorrectly. Instead of sorting signed integers as you would expect them to be sorted, all negative numbers are considered to be "greater" than all positive numbers.

IntKey new implementation: 
```
impl<T: Endian> IntKey<T> {
    pub fn new(val: T) -> Self {
        IntKey {
            wrapped: val.to_be_bytes().into(),
            data: PhantomData,
        }
    }
}
```

The new implementation converts the i32 number to big endian bytes which doesn't preserve the sorting order.

My workaround was to restrict my range query with a max of the most negative number:
```
    let zero_winnings_key = leaderboard()
        .idx
        .winnings
        .index_key((I32Key::from(0), b"".to_vec()));
    let most_negative_key = leaderboard()
        .idx
        .winnings
        .index_key((I32Key::from(-2147483648), b"".to_vec()));

    let res = leaderboard()
        .idx
        .winnings
        .range(
            deps.storage,
            Some(Bound::inclusive(zero_winnings_key)),
            Some(Bound::exclusive(most_negative_key)),
            Order::Descending,
        )
        .take(limit)
        .collect::<StdResult<Vec<_>>>()?;
```
This fits my use case because I don't need the negative values when querying, but is quite counterintuitive and took me a long time to figure out what was going on.

**Comment by ethanfrey** [comment]
> The problem is that we're using the internal representation to define the order, and the internal representation of negative numbers is based on two's complement, in which the most significant bit is used as sign bit. So that, lexicographically, negative numbers come after positive numbers.

There is no way to easily scan besides byte order. I think a new byte representation for signed ints could be interesting.

I believe if we toggle the first bit on big endian, this will actually provide the ordering we want.

```
let mut be = value.to_be_bytes();
be[0] = be[0] ^ 0xf0;
```

Is that correct?

If so, we can use IntKey and UintKey as two types with different serialization/parsing logic and everyone will be happy.

**Comment by maurolacy** [comment]
> > The problem is that we're using the internal representation to define the order, and the internal representation of negative numbers is based on two's complement, in which the most significant bit is used as sign bit. So that, lexicographically, negative numbers come after positive numbers.
> 
> There is no way to easily scan besides byte order. I think a new byte representation for signed ints could be interesting.
> 
> I believe if we toggle the first bit on big endian, this will actually provide the ordering we want.
> 
> ```
> let mut be = value.to_be_bytes();
> be[0] = be[0] ^ 0xf0;
> ```
> 
> Is that correct?

Almost. It's 
```rust
be[0] ^= 0x80;
```

But yes, this is a good idea, and it will in fact solve the ordering issue.
When we deserialize, we can easily fix / revert this, and restore the original value. So, this will require a deserializing `range` to work properly. If not, raw signed and unsigned ints will be exchanged, and you would be able to access them because they leak from the raw `range`.That, or we would have to provide our own, sanctioned version of `from_be_bytes().

> 
> If so, we can use IntKey and UintKey as two types with different serialization/parsing logic and everyone will be happy.
