### ISSUE TITLE
Implement attribute macro for trait interface generating boilerplate specific for cw1-whitelist

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/cw-plus#495]
Part of #493, follow up of #494 

* [x] Generate  `ExecMsg` from contract trait
* [x] Generate `QueryMsg` from contract trait
* [ ] Generate dispatch function for dispatching exec msg
* [ ] Generate dispatch function for dispatching query msg
* [ ] If entry points turns out being tricky - generate them, or provide tool for making them clear

**Comment by egasimus** [comment]
Yo, these past few months we've been up to [more or less the same thing](https://github.com/hackbg/fadroma/tree/21.12/lib/derive-contract). (Contract traits too - though ours are in a private repo that we'll make public once it passes audits etc.) Good to see the design of the platform has been guiding everyone in the same direction :)

We've implemented ours on top of Secret Network's fork of CW 0.10, but word has it 0.16 is coming to SN soon. Wanna share the workload?

**Comment by hashedone** [comment]
@egasimus First of all I am more than happy that someone besides me figured out the same idea. You are the second one who pointed me something similar after looking for my proposal (the other one was not CW-specific), which basically means there is a need for such solution.

I actually already started my implementation of contract generation. I have no problem with sharing workload, but we would need to decide what exactly shape are we modeling. What I lack in your approach is... documentation, so it is hard for me to what exact contract are you expecting to generate, and how do you want to handle next things. We started with creating "generated" version of contract created by hand (and actually even before it - I sketched a brief proposal about that: https://github.com/CosmWasm/cw-plus/issues/391). Possibly you have something similar, but you didn't link it and I cannot find it quickly - if there is something then please link so maybe we can influence this.

But if we are able to find some common sense of where are we going with that I think that sharing the workload would be very nice.

One think you should know about our solution is that for now it seems that it seems to be more gas costly than traditional contracts, at least for trivial contracts (it is hard to tell for now if its overhead is constant and would diminish for real life contracts or not). However we don't have a way to profile them correctly and I personally cannot figure out what is actually slowing down so much (see #567). If it is not a problem for you then it is ok, but if you have some idea how to improve the gas usage then it can be very helpful.

If you want we could probably setup some call or something to talk about this.

**Comment by uint** [comment]
This is part of [Sylvia](https://github.com/CosmWasm/sylvia/tree/main/sylvia) now. Closing!
