### ISSUE TITLE
Benchmark "ng" vs. "classic" frameworks

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#505]
Once the "ng" framework is more or less stable, let's create benchmarks to compare contract instantiation, execution, and querying on both versions. By example using the cw1-whitelist contracts as baseline / reference.

Results must be pretty similar, but better to measure and track gas usage over time.

**Comment by JakeHartnell** [comment]
Awesome gas profiling tool by @de-husk: https://github.com/de-husk/cosm-orc
