### ISSUE TITLE
Fix min threshold and vote power bugs in cw3-flex-multisig

### ISSUE THREAD

**Issue by ueco-jb** [CosmWasm/cw-plus#527]
While reusing contracts in other repository, we noticed that implementation of `cw3-flex-multisig` contained couple of issues.

- [ ] member weight before proposing and voting should be checked for >= 1 (0 weight voter can't perform those operation)
- [ ] threshold value should be required >= 0.5

**Comment by maurolacy** [comment]
After this, it would be good to add similar checks / fixes to cw3-fixed-multisig (here or in another PR).

**Comment by ueco-jb** [comment]
> After this, it would be good to add similar checks / fixes to cw3-fixed-multisig (here or in another PR).

https://github.com/CosmWasm/cw-plus/issues/551
