### ISSUE TITLE
Remove schemas, and publish them with artifacts on release tags

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#529]

**Comment by ethanfrey** [comment]
Yes, let's do this for 0.11. Nice change

**Comment by maurolacy** [comment]
Closed in error. I can do this for cw-plus.

**Comment by ueco-jb** [comment]
Oh sorry, didn't notice that this merged PR was from lendex.

**Comment by maurolacy** [comment]
As punishment you now have to review #589 :-)
