### ISSUE TITLE
Improve `MultiIndex` pk deserialization

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#531]
~~Signal the primary key deserialization type of `MultiIndex` using a `PK` trait or similar, like in `UniqueIndex`~~. (done in #568)

In passing, ~~rename `K` to `IK` (Index Key) for clarity in both indexes~~. (done in #569)

If possible, make those `PK` traits automatic / inherited from the `IndexedMap` specification. That means, better encapsulation / coupling between `IndexedMap` and the `*Index` impls.

**Comment by maurolacy** [comment]
Breaking change, as it would change the internal representation of the index key. For 0.11, or pehaps, 0.12.

**Comment by ethanfrey** [comment]
Is this done? @maurolacy 

If so, let's close. If not, can you improve the description so we can follow up on it?

**Comment by maurolacy** [comment]
This is "closed" by the `index_trait` procedural macro.

Implementing the third point in the description would require a significant refactor of `IndexedMap` and associated indexes.

So, I would say, let's close it as solved through a workaround.
