### ISSUE TITLE
handle function

### ISSUE THREAD

**Issue by wotori** [CosmWasm/cw-plus#563]
I want to use contract as It Is. For now I just copy-paste the code into my project and deploy It. But I see in README.md that I can do the same somehow much easily, as said ```Basically, you just need to write your handle function and import 
`cw20_base::contract::handle_transfer`, etc and dispatch to them.```
Could you share the link, or show the example of such a usage of the package? 

p.s.
watching [tutorial from 2020](https://www.youtube.com/watch?v=pm6VX5ueT2k) and lot's of things hugely changed. Is there kind of quick start video with latest updates in code?

**Comment by orkunkl** [comment]
This doc https://docs.cosmwasm.com/dev-academy/develop-smart-contract/intro teaches you exactly that
