### ISSUE TITLE
`base-helpers.ts` doesn't belong to `contracts`

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/cw-plus#566]
~~`contracts` structure is assumed by the wasm workspace building utility. Because of `base-helpers.ts` file it is now impossible to easly build workspace with it.~~ (it is actually working with newest version, but it still doesn't belong here prob). Either this file should move to some better place (some utilities? it is not a contract so it doesn't belong there semantically) or workspace builder should be altered to better detect what to build.

**Comment by ethanfrey** [comment]
I proposed a new repo for this. I will follow up with @orkunkl on this one.

Let's move all the ts helpers to a repo with a proper npm package and build system (so we can use typescript) and a CI to test they work against these contracts. They can be pushed to npm and people can just import these.

I know you have some larger ideas of a framework, but I think it would be very useful to move them out of this repo in the short term, so they can be properly tested and maintained. Let me know what you need to do so.

**Comment by orkunkl** [comment]
For temporary, we can setup an `InterWasm/ts-plus` repo to contain these helpers @findolor

**Comment by orkunkl** [comment]
Will be moved to https://github.com/InterWasm/cw-plus-helpers

**Comment by ethanfrey** [comment]
Thanks Orkun
