### ISSUE TITLE
Investigate JSON Schema -> html/md generator

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cw-plus#573]
It would be nice to auto-generate a static web page to show a contract's API.
If we build this in the CI and commit it, we could also easily view diffs between versions of a contract.

Let's first investigate what tools there are that can auto-generate sites from JSON Schema and compare them. Then see what other annotations we can add to our schemas to help with the generation.

**Comment by ethanfrey** [comment]
@pyramation has done a lot of relevant work in https://github.com/CosmWasm/ts-codegen

@uint if you have a clear ask / requirement, it would probably be best to talk with Dan and see if he could add another output mode to ts-codegen (it has like 5 formats, seems easy enough to add another if it is well spec'ed)

**Comment by pyramation** [comment]
interesting, not to tangent too far, but I've also been thinking about generating docs/examples for usage of the ts-codegen.

I've been building a few packages and would be nice to eventually have the entire API documented with even some generated JS examples.

I can see two types of docs for two different use cases, but related in this docgen sense:

1. pure Rust-based (JSON schema derived) methods and props that describe types, understanding contract structure.
2. ts-codegen generated examples to get users quickly building apps on contracts in JS

**Comment by ethanfrey** [comment]
Yes, this issue is about (1).

We definitely need better docs on "zero to hero" for ts-codegen usage. Let's collaborate on that between Confio and Cosmology. I'd be happy to include this in our academy and official docs.

**Comment by uint** [comment]
I'm not sure if (1) belongs in `ts-codegen` strictly, since it seems like an aid to everyone who is **not** using the ts-codegen, but I want to take a look if there's anything useful about what `ts-codegen` does to interpret the data.

**Comment by pyramation** [comment]
I haven't tested, but found these for research:

- [ ] https://github.com/adobe/jsonschema2md
- [ ] https://github.com/bootprint/bootprint-json-schema
- [ ] https://github.com/interagent/prmd

**Comment by uint** [comment]
Just not to forget: one thing that came up when we talked about it before was providing examples of valid JSON messages with realistic data.

**Comment by uint** [comment]
This probably doesn't belong to this repo.
