### ISSUE TITLE
Cannot import non "library" features in dev-dependencies 

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/cw-plus#577]
I am currently building a NFT project that imports `cw721-metadata-onchain`. I assume the same problem will be relevant here.

Imported cw721-metadata-onchain with `library` feature in dependencies, but since I am using multitest library for testing, I need `entry` package which is ignored in dev-dependencies. This makes it impossible to use multitest and have reduced binary size at the same time.

Made research and found updating to [resolver](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) to version 2. Yet I could not make it work and above my rust knowledge :(

**Comment by ethanfrey** [comment]
This is an issue in the source repo: https://github.com/CosmWasm/cw-nfts/blob/main/contracts/cw721-metadata-onchain/src/lib.rs#L33-L67

Basically, you have two choice:
1. Just copy these minimal execute/instaniate/query definitions into your test helpers
2. Export them, but wrap each entry point definition in library (a bit more verbose and change upstream)

The first would be to add something like this to your multitest test helper:

```rust
use cw721_onchain_metadata::Cw721MetadataContract;

pub fn instantiate(
        deps: DepsMut,
        env: Env,
        info: MessageInfo,
        msg: InstantiateMsg,
    ) -> StdResult<Response> {
        Cw721MetadataContract::default().instantiate(deps, env, info, msg)
    }
```

The second would be to change cw721_onchain_metadata like:

```rust
pub mod entry {
    use super::*;

    use cosmwasm_std::entry_point;
    use cosmwasm_std::{Binary, Deps, DepsMut, Env, MessageInfo, Response, StdResult};

    // This makes a conscious choice on the various generics used by the contract
    #[cfg_attr(not(feature = "library"), entry_point)]
    pub fn instantiate(
        deps: DepsMut,
        env: Env,
        info: MessageInfo,
        msg: InstantiateMsg,
    ) -> StdResult<Response> {
        Cw721MetadataContract::default().instantiate(deps, env, info, msg)
    }
}
```

Which could them be imported

**Comment by ethanfrey** [comment]
Good question, but closing as this is answered and no work to do ins cw-plus
