### ISSUE TITLE
Duplicate accounts in cw20 initial balances causes unrecoverable inconsistent state

### ISSUE THREAD

**Issue by harryscholes** [CosmWasm/cw-plus#626]
If `initial_balances` contains one or more duplicate accounts, these accounts will have the balance of the final balance saved to state, whilst the `total_supply` will be the sum over all initial balances provided.

https://github.com/CosmWasm/cw-plus/blob/501efe8fb5151f658380a87c30091a2851e556e5/contracts/cw20-base/src/contract.rs#L154-L162

Example:

```rust
#[test]
fn inconsistent_total_supply_with_duplicate_accounts_in_initial_balances() {
    let mut deps = mock_dependencies(&[]);
    let instantiate_msg = InstantiateMsg {
        name: "Cash Token".to_string(),
        symbol: "CASH".to_string(),
        decimals: 9,
        initial_balances: vec![
            Cw20Coin {
                address: String::from("addr0000"),
                amount: Uint128::from(1u128),
            },
            Cw20Coin {
                address: String::from("addr0000"),
                amount: Uint128::from(1u128),
            },
        ],
        mint: None,
        marketing: None,
    };
    let info = mock_info("creator", &[]);
    let env = mock_env();
    instantiate(deps.as_mut(), env, info, instantiate_msg).unwrap();

    let token_info = query_token_info(deps.as_ref()).unwrap();
    assert_eq!(token_info.total_supply, Uint128::new(2));
    assert_eq!(get_balance(deps.as_ref(), "addr0000"), Uint128::new(1));
}
```

Should we assert that all accounts in `initial_balances` are unique? Happy to make a PR for this if there is interest.

NB this was found in an audit of Mars protocol in a contract that was forked from the cw-plus cw20-base contract.

**Comment by ethanfrey** [comment]
Thank you for this report. It would be good to assert that all addresses in the initial_balances list only appear once, and fail if there are duplicates

**Comment by maurolacy** [comment]
@harryscholes do you want to provide a fix fix this? I'll assign it to you then.

**Comment by harryscholes** [comment]
Thanks @maurolacy. I'll complete this in approx two weeks time
