### ISSUE TITLE
cw20 allowance expiration can be set to a block height or timestamp in the past

### ISSUE THREAD

**Issue by harryscholes** [CosmWasm/cw-plus#628]
Expirations are not validated when allowances are created,
https://github.com/CosmWasm/cw-plus/blob/fa0c5ac7b3a1575b436c2040c371afd7e68e9c05/contracts/cw20-base/src/allowances.rs#L28

only when they are used https://github.com/CosmWasm/cw-plus/blob/fa0c5ac7b3a1575b436c2040c371afd7e68e9c05/contracts/cw20-base/src/allowances.rs#L95

This is not a huge problem, as the expiration can be updated to a future block height or timestamp, or removed entirely. Should we add validation that the block height or timestamp is in the future when creating a new allowance? Happy to make a PR for this if there is interest.

NB this was found in an audit of Mars protocol in a contract that was forked from the cw-plus cw20-base contract.

**Comment by ethanfrey** [comment]
Happy for this addition. It seems like it slipped off our plate
