### ISSUE TITLE
[cw3-flex/fixed-multisig] Status changes after voting and proposal expiration

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#630]
A number of bugs were discovered in voting contracts, part of ~~soon to be~~ open-sourced poe-contracts. (See [#12](https://github.com/confio/poe-contracts/issues/12), [#14](https://github.com/confio/poe-contracts/issues/14), and [#16](https://github.com/confio/poe-contracts/issues/16)).

Let's backport / adapt the fixes and tests to cw3-flex-multisig and cw3-fixed-multisig (if applicable).

**Comment by mccordnate** [comment]
Would love to see this improvement

**Comment by maurolacy** [comment]
@tom will take care of this, and the follow-ups.
