### ISSUE TITLE
[cw3-flex/fixed-multisig] Reject proposals early

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#665]
After a similar issue in dao-contracts: https://github.com/DA0-DA0/dao-contracts/issues/169.

The task is then backporting / adapting that logic here, and adding the equivalent functionality to fixed-multisig as well.

**Comment by Callum-A** [comment]
My fix for DAO DAO is available [here](https://github.com/DA0-DA0/dao-contracts/pull/181). I am happy to undertake this myself or if anyone else wants to pick this up and cannot understand my solution, feel free to reach out!

**Comment by maurolacy** [comment]
Please submit a PR, and we review it and merge it.

**Comment by maurolacy** [comment]
Closed by #668.
