### ISSUE TITLE
Change `MultiIndex` index function signature to include the pk

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-plus#670]
It would be good that the `MultiIndex` index function signature, instead of being `fn(&T) -> IK`, was `fn(&PK, &T) -> IK` instead.

That way, the pk (or parts of it) can be used for indexing. And so the index keys don't have / need to come from the values alone.

**Comment by ewoolsey** [comment]
Any progress being made on this?

**Comment by maurolacy** [comment]
Shouldn't be too hard to do this change. Delayed mostly because it's a breaking change. Will give it a try.
