### ISSUE TITLE
error: could not compile `ff` when running cargo test on cw20-base contract

### ISSUE THREAD

**Issue by Odelya** [CosmWasm/cw-plus#714]
I cloned the repository and ran cargo test on cw20-base contract, however, I get

error: could not compile `ff`

It seems that ff is not updated to its latest version, but I am not sure which library requires it and which ff is set there to "0.10.1"

**Comment by hashedone** [comment]
Hi, I just checked it and cannot reproduce - both cw20 and the whole workspace is passing tests with `cargo test`. It works also after removing `Cargo.lock` so it doesn't look like it is problem with any dependencies. Could you check `cargo` version you are using (`cargo --version`) so I can check if this way I would be able to reproduce it?

**Comment by Odelya** [comment]
I installed it via rustup and I’m using the latest version which is 1.6.00 on m1 Mac 

Thanks!

**Comment by hashedone** [comment]
The dependency to `ff="0.10.1"` is transitive from `cosmwams-crypto` and if it should be updated it is there (in particular `k256` package to be upgraded to a newer version), however, it seems not to be trivial as API changed slightly (minor changes, but I need to go through them). Also, I need to ensure that we can just update dependencies without breaking API. Will take a deeper look probably on Tuesday.

Anyway, it puzzles me why with the newest Rust, the compilation fails - it should be able to checkout the older version of ff (0.10.1 in this case) as it is not yanked. Do you mind pasting me your whole build log? I assume you test pure cw20 contract with no changes, right?

**Comment by Odelya** [comment]
I ran cargo test from the root and now it passed fine. I will close this issue for now. Thanks @hashedone
