### ISSUE TITLE
Unable to upload cw20_base wasm file on terra-station

### ISSUE THREAD

**Issue by Odelya** [CosmWasm/cw-plus#716]
I am trying to upload an optimized version of cw20_base contract to my localterra like this:

 ```
 const terra = new LCDClient({URL: 'http://localhost:1317', chainID: 'localterra',});
  const wallet = terra.wallet(mk);
  const storeCode = new MsgStoreCode(
    wallet.key.accAddress,
    fs.readFileSync('../artifacts/cs20_base.wasm').toString('base64'),
  );

  const storeCodeTx = await wallet.createAndSignTx({msgs: [storeCode]});
```

However, I am getting:

 **code: 3,
 message: 'failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): store wasm contract failed: invalid request',**

is it working with terra network? if so, how?

**Comment by Odelya** [comment]
I checkout to tag `v0.9.2` which depends on `cosmwasm-std version = "0.16.0"` and now it works. It could be related to that library. What do you suggest to do?

**Comment by octalmage** [comment]
Terra is on CosmWasm 0.16 which means you’ll need to use branch 0.9.x

**Comment by taitruong** [comment]
I am all new to this and have the same issue. Trying this example: https://github.com/terran6/nft-on-terra



My Cargo.toml file uses cw-plus v0.9.2 and CosmWasm 0.16.0. It looks like this:
`[package]
name = "cw721-metadata-onchain"
version = "0.9.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Example extending CW721 NFT to store metadata on chain"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "artifacts/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.5
"""

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw721 = { version = "0.9.2" }
cw721-base = {version = "0.9.2", features = ["library"] }
cosmwasm-std = { version = "0.16.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
`

**Comment by ethanfrey** [comment]
Terra (both classes and terra2) are using cosmwasm 1.0 afaik. Closing this
