### ISSUE TITLE
Allow burn to have a callback just like Send

### ISSUE THREAD

**Issue by ferencdg** [CosmWasm/cw-plus#717]
it would be nice to have contracts (usually the owner) notified that certain tokens have been burned just like it is done with the Send message

**Comment by ueco-jb** [comment]
Is `cw-plus` right place for such request?
Could you share more details what you have in mind with `Send` message callback?

**Comment by ferencdg** [comment]
> Is `cw-plus` right place for such request? Could you share more details what you have in mind with `Send` message callback?

sorry what I meant is your cw20 implementation
https://github.com/CosmWasm/cw-plus/blob/main/packages/cw20/README.md

the send allows calling back a contract:
Send{contract, amount, msg}

however the Burn doesn't
Burn{amount}

but contracts might want to be notified too that some users burnt some tokens (possibly a token managed by the contract that needs to be called)

**Comment by mr-rooftop** [comment]
yes that would be very useful!

**Comment by ethanfrey** [comment]
Currently, you could `Send` it to the contract, and that contract will do whatever action is expected, and then return another message to burn the tokens it just received.

Understood that is not the UX you want, but it will serve as a placeholder

**Comment by ethanfrey** [comment]
Also, `Burn` was designed as an analog to `Transfer` (which doesn't call a contract).
We would need a new name for this method. And I'm still not sure it would be that heavily used such that my workaround (above) wouldn't be sufficient

**Comment by ferencdg** [comment]
thanks, I was aware of this workaround, just hoped there will be a direct
support

if you think it is an unnecessary feature, then please close this ticket,
thanks
