### ISSUE TITLE
Wrong/unclear explanation in IndexedMap docs

### ISSUE THREAD

**Issue by albertchon** [CosmWasm/cw-plus#718]
The docs for IndexedMap state
https://github.com/CosmWasm/cw-plus/blob/119032e06b943abb299d295bd2e0eebdd6c85e6a/packages/storage-plus/README.md?plain=1#L488-L489

However in the latest cw-nfts code (using cw-storage-plus v0.13.2), this is no longer the case
https://github.com/CosmWasm/cw-nfts/blob/584e01526048334b87a85a6c69f54109727efb5a/contracts/cw721-base/src/state.rs#L121-L126

It seems this change arose from @maurolacy's removing of the PK default from MultiIndex, so that "the PK type must match the encompassing `IndexedMap` primary key type, or its owned variant".

**Comment by maurolacy** [comment]
cw-nfts code should be modified to conform to this new format / convention, yes.
