### ISSUE TITLE
Restructure `Index` trait to allow for more extensive `Index` struct implementation.

### ISSUE THREAD

**Issue by y-pakorn** [CosmWasm/cw-plus#757]
This should not affect/or break anything. Trait change allows for the implemented `Index` struct can access both `old_data` and `data` and act accordingly.

For the ideas, In some cases, we will not need to update the indexes every update, only handle the first save and remove. This can be called `ConstantMultiIndexes`.

Or we can update the indexes whether the condition of the data updated is met. This can be called `ConditionalMultiIndexes`.

```rust
pub trait Index<T>
where
    T: Serialize + DeserializeOwned + Clone,
{
    fn update(
        &self,
        store: &mut dyn Storage,
        pk: &[u8],
        old_data: Option<&T>,
        data: Option<&T>,
    ) -> StdResult<()>;

    fn save(&self, store: &mut dyn Storage, pk: &[u8], data: &T) -> StdResult<()> {
        self.update(store, pk, None, Some(data))
    }

    fn remove(&self, store: &mut dyn Storage, pk: &[u8], old_data: &T) -> StdResult<()> {
        self.update(store, pk, Some(old_data), None)
    }
}
```

**Comment by maurolacy** [comment]
For what I can see in the associated PR, this is just cosmetics: Moving `replace`'s functionality inside of `update`, and handling both `save` and `remove` in terms of `update`.

I wouldn't merge this unless there's a good reason that indicates this is better than the current implementation.
