### ISSUE TITLE
`Prefix::keys` method never fails

### ISSUE THREAD

**Issue by ShadoySV** [CosmWasm/cw-plus#766]
Keys are just skipped if deserializating of its key or value fails.
That's because de_fn returns Result which implements Iterator as well and, being iterated, returns nothing in case of error value
https://github.com/CosmWasm/cw-plus/blob/b2a15611d663109d1794e2827f1cf25038e5b9a6/packages/storage-plus/src/prefix.rs#L188
Is it desired behavior?

**Comment by maurolacy** [comment]
Good point. I think this arose because of backwards compatibility reasons when implementing key deserialisation on top of the existing API. I agree this would be good to change.

**Comment by ShadoySV** [comment]
Thank you
