### ISSUE TITLE
Can I cover all tests with cw_multi_test?

### ISSUE THREAD

**Issue by siulee2** [CosmWasm/cw-plus#771]
Hi,
I'm here for hear what you guys think about this topic

Recently, I wrote both unit test and integration test code.
Integration test codes are written with `cw_multi_test`.

After that, I thought that It seems like only `cw_multi_test` is enough for tests code.
If I have to maintain unittest code. It will make it difficult for us to make changes to the cosmwasm code.

Is it necessary to write a unit test code? 
what do u think,,

**Comment by ueco-jb** [comment]
This is kind of riddiculous question.
Yes, you should write unit tests for things, that are difficult or can't be straightforward covered by multi tests.
