### ISSUE TITLE
Standardize protocol events

### ISSUE THREAD

**Issue by uint** [CosmWasm/cw-plus#823]
As far as I understand, our `README.md` files like [this one](https://github.com/CosmWasm/cw-plus/blob/main/packages/cw20/README.md) are protocol specs. Events emitted don't seem to be part of the protocol spec, and yet [client software like a cw20 wallet or block explorer might rely on the format of emitted events to index transactions](https://docs.cosmos.network/main/core/events).

It might be tempting to change the events emitted in a concrete implementation like [`cw20-base`](https://github.com/CosmWasm/cw-plus/tree/main/contracts/cw20-base) to suit clients, but the whole point of having a specification is to assume `cw20-base` isn't the only implementation. IMO any changes to the protocol should be well communicated and start with the specification, not our "minimal examples".

**Comment by ethanfrey** [comment]
I agree to standardise and freeze these (we may want to review them again and refine them first)

Note there was some discussion ages ago to make some sort of structs that represent events, that could also emit some "json-schema-like" format to describe what to expect. This is a bonus task, but may want to investigate when you formalise these.

One rough idea:

```
// embedded in 'wasm' event, via add_attribute
#[event]
pub struct TransferEvent {
  pub sender: String,
  pub recipient: String,
  // question: String or Uint128
  pub amount: String,
}

// complete event, created via add_event
#[event(type="add_member")]
pub struct AddMemberEvent {
  pub address: String,
  // question: String or u64
  pub weight: String,
}
```

**Comment by uint** [comment]
That looks like a good thing to include in the new schema format. I think filling out the specs comes first, but will definitely take a go at this.
