### ISSUE TITLE
Remove `cw1155` and `cw1155-base`

### ISSUE THREAD

**Issue by uint** [CosmWasm/cw-plus#830]
These are unmaintained.

**Comment by AshutoshModanwal21** [comment]
Hi team, 
it was nice while working with CW packages, 
In my project requirement, there is need of this package & its contract, for developing NFT with fixed quantity of replicas, 
but as we see this package has been removed from the Cosmwasm, 
so please anyone suggest me any alternatives of this package to achieve the same functionalities was holded by cw115-base.

**Comment by ueco-jb** [comment]
Hey @AshutoshModanwal21, I would recommend you checking out some of Stargaze repositories. It's a leading chain in cosmos that handles NFTs.
https://github.com/public-awesome/cw-nfts
https://github.com/public-awesome/cw-ics721
