### ISSUE TITLE
Workspace optimizer build failed

### ISSUE THREAD

**Issue by djpesic** [CosmWasm/cw-plus#838]
I have downloaded latest version of the cw-plus repo. I started build and got following:

docker run --rm -v "$(pwd)":/code \
>   --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
>   --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
>   cosmwasm/workspace-optimizer:0.12.6
1.60.0-x86_64-unknown-linux-musl (default)
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
Building artifacts in workspace ...
Found workspace member entries: ["packages/*", "contracts/*"]
Package directories: ["contracts/cw1-subkeys", "contracts/cw1-whitelist", "contracts/cw20-base", "contracts/cw20-ics20", "contracts/cw3-fixed-multisig", "contracts/cw3-flex-multisig", "contracts/cw4-group", "contracts/cw4-stake", "packages/controllers", "packages/cw1", "packages/cw2", "packages/cw20", "packages/cw3", "packages/cw4"]
Contracts to be built: ["contracts/cw1-subkeys", "contracts/cw1-whitelist", "contracts/cw20-base", "contracts/cw20-ics20", "contracts/cw3-fixed-multisig", "contracts/cw3-flex-multisig", "contracts/cw4-group", "contracts/cw4-stake"]
Building "contracts/cw1-subkeys" ...
warning: profile package spec `cw1155-base` in profile `release` did not match any packages
   Compiling cw1 v0.16.0 (/code/packages/cw1)
   Compiling cw2 v0.16.0 (/code/packages/cw2)
   Compiling cw1-whitelist v0.16.0 (/code/contracts/cw1-whitelist)
   Compiling cw1-subkeys v0.16.0 (/code/contracts/cw1-subkeys)
error[E0599]: no variant or associated item named `response_schemas` found for enum `cw1_subkeys::msg::QueryMsg` in the current scope
  --> contracts/cw1-subkeys/src/bin/schema.rs:8:5
   |
8  | /     write_api! {
9  | |         instantiate: InstantiateMsg,
10 | |         execute: ExecuteMsg,
11 | |         query: QueryMsg,
12 | |     }
   | |_____^ variant or associated item not found in `cw1_subkeys::msg::QueryMsg<_>`
   |
   = note: this error originates in the macro `write_api` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0599`.
error: could not compile `cw1-subkeys` due to previous error
thread 'main' panicked at 'assertion failed: error_code.success()', src/main.rs:77:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Before that, i run rustup update and set toolchain to nightly.

**Comment by ueco-jb** [comment]
Duplicate.
https://github.com/CosmWasm/cw-plus/issues/828
