### ISSUE TITLE
Error message on Kujira Fin 

### ISSUE THREAD

**Issue by tarponjohn** [CosmWasm/cw-plus#889]
Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: Invalid price: execute wasm contract failed [!cosm!wasm/wasmd@v0.42.0/x/wasm/keeper/keeper.go:395] With gas wanted: '100000000' and gas used: '124151' : unknown request...what does this mean? just loaded some axUSDC onto Kujira (first time) and now trying to trade into some Kuji ...can't do anything

**Comment by tarponjohn** [comment]
strange that my wallet only in READ ONLY MODE ?

**Comment by webmaster128** [comment]
This question is unrelated to cw-plus. Please ask the Kujira folks in such chain-specific cases. Thanks!
